- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2,db_and_web_server3
  tasks:
  - include: tasks/deploy_installation.yml

  - include: tasks/deploy_db.yml
  
  - include: tasks/deploy_web.yml

