- name: Start MySQL Service
  service:
    name: mysql
    state: restarted
   
- name: Create Application Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  
- name: Create Database User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present   
    host: '%'
